spring.application.name=marketpulse

spring.datasource.url=jdbc:postgresql://localhost:5432/marketpulse
spring.datasource.username=postgres
spring.datasource.password=MarketPulse@123

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
