CREATE TABLE stocks (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        symbol VARCHAR(50) UNIQUE NOT NULL,
                        company_name VARCHAR(255) NOT NULL,
                        exchange VARCHAR(50) NOT NULL,
                        sector VARCHAR(100)
);